# Generated by Django 2.2.10 on 2020-09-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.DeleteModel(
            name='MiLista',
        ),
    ]
