# Generated by Django 2.2.10 on 2020-09-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_auto_20200902_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
